# Нахождение уравнения плоскости по точкам, через которые она проходит.

Уравнение плоскости в 3-х мерном пространстве задаётся уравнением: \begin{matrix}
z = ax + by + c
\end{matrix}


Уравнение плоскости однозначно задаётся 3 точками через которые она проходит.
Таким образом легко понять, что если мы знаем координаты точек, через которые проходит плоскость, то в уравнении выше у вас 3 переменных: a, b, c. А значения x, y, z нам известны для 3 точек.
Если плоскость проходит через точки (1;-6;1), (0;-3;2) и (-3;0;-1), то мы легко можем найти коэффициенты, подставив значения соответствующих координат для всех 3 точек в уравнение выше и получить систему из 3 уравнений, которая затем используется для составления матрицы: \begin{pmatrix}
1& -6 & 1
\\ 
0 & -3 & 1
\\ 
-3 & 0 & 1
\end{pmatrix}

А также вектор свободных членов: \begin{pmatrix}
1
\ 
2
\
-1
\end{pmatrix}

In [5]:
import numpy as np

m = np.array([[1., -6., 1.], [0., -3., 1], [-3, 0, 1]])
v = np.array([1., 2., -1.])

np.linalg.solve(m, v)

array([2., 1., 5.])

Ответ: уравнение искомой плоскости в пространстве задаётся уравнением z = 2x + y + 5

# Произвольные матрицы уравнений и решений


In [8]:
matrix = np.random.uniform(-20., 100., (4, 4))
print(matrix)
vec = np.random.uniform(-20., 100., (4, 1))
print(vec)
np.linalg.solve(matrix, vec)

[[ 43.34951311 -19.94224474  54.21055599  28.54922287]
 [ 47.77493978   1.81376561  53.90381902  31.31676901]
 [ 91.31541817  16.3778718   -6.55630636  26.26389007]
 [-10.90239254   8.5651597   71.74041152  52.82606331]]
[[43.6299613 ]
 [-2.70685347]
 [13.95645529]
 [-0.44322837]]


array([[ 0.01714457],
       [-2.36362512],
       [-0.9749016 ],
       [ 1.70234826]])

# Метод Крамера


In [1]:
import numpy as np

In [5]:
n = np.random.randint(1, 7)
a = np.random.uniform(-20., 100., (n, n))
b = np.random.uniform(-20., 100., (n, 1))
print(f"The matrix of the equation:\n {a}")
print(f"The matrix of the free terms of the equation:\n {b}")
det = np.linalg.det(a)
print(f"The main determinant: {det}")
print("The Kramer algorithm: ")
for j in range(n):
    a_sav = a.copy()
    a_sav[::, j] = b[::, 0]
    print(a_sav)
    det_x = np.linalg.det(a_sav)
    print(f"The minor determinant number {j + 1}: {det_x}")
    x = det_x / det
    print(f"The {j + 1} root of the equation: {x}")

The matrix of the equation:
 [[ 24.88253275  82.74066442  81.06812728  54.88462965  74.40965796]
 [ 36.17160166  25.02902067 -10.45753698  97.6267258   77.76361442]
 [ 81.77580652  69.50578164   0.23114888  62.2449725   18.75661774]
 [ 20.48483616  36.51403248  49.22799368  59.06105178 -12.93240583]
 [ 37.51011042  77.46890253  79.2949131   -2.60142186  -8.15088509]]
The matrix of the free terms of the equation:
 [[  3.78095474]
 [-19.574148  ]
 [ 75.57543813]
 [ 33.53440075]
 [ 44.12447613]]
The main determinant: -375901204.6272254
The Kramer algorithm: 
[[  3.78095474  82.74066442  81.06812728  54.88462965  74.40965796]
 [-19.574148    25.02902067 -10.45753698  97.6267258   77.76361442]
 [ 75.57543813  69.50578164   0.23114888  62.2449725   18.75661774]
 [ 33.53440075  36.51403248  49.22799368  59.06105178 -12.93240583]
 [ 44.12447613  77.46890253  79.2949131   -2.60142186  -8.15088509]]
The minor determinant number 1: 653958230.7048887
The 1 root of the equation: -1.7397077281340654